import Head from 'next/head'
import { Box, Typography, Autocomplete, TextField } from '@mui/material'
import { Inter } from '@next/font/google'
import Header from '@/components/Header'
import Search from '@/components/Search'
import PageLayout from '@/components/PageLayout'

const inter = Inter({ subsets: ['latin'] })

const styles = {
    root: {
        height: '100vh',
        // backgroundColor: '#32323e',
        display: 'flex',
        flexDirection: 'column',
    },
}

export default function Home() {
    return (
        <>
            <Head>
                <title>COL - сравненивайте цены в разных странах мира</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageLayout>
                <Search />
            </PageLayout>
        </>
    )
}
