import React from 'react'
import Head from 'next/head'
import { Box } from '@mui/material'
import RootLayout from './RootLayout'
import { LocalesMap, useLocale } from '@/shared/utils'

const locales: LocalesMap = {
    ru: {
        title: 'COL - сравненивайте цены в разных странах мира',
        description: '',
    },
    en: {
        title: 'COL - compare prices around the world',
        description: '',
    },
}

const styles = {
    content: {
        maxWidth: '1290px',
        margin: 'auto',
    },
}

export default function PageLayout({ children }: Pick<React.HTMLAttributes<HTMLDivElement>, 'children'>) {
    const t = useLocale(locales)
    return (
        <>
            <Head>
                <title>{t('title')}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <RootLayout>
                <Box sx={styles.content}>{children}</Box>
            </RootLayout>
        </>
    )
}
