import React from 'react'

import { Box } from '@mui/material'
import Head from 'next/head'
import RootLayout from './RootLayout'

const styles = {
    content: {
        maxWidth: '1290px',
        margin: 'auto',
    },
}

export default function PageLayout({ children }: Pick<React.HTMLAttributes<HTMLDivElement>, 'children'>) {
    return (
        <>
            <Head>
                <title>COL - сравненивайте цены в разных странах мира</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <RootLayout>
                <Box sx={styles.content}>{children}</Box>
            </RootLayout>
        </>
    )
}
