name: deploy-actions

on:
    push:
        branches:
            - '**'

env:
    REPO_NAME: col-client
    IMAGE_TAG: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/col-client:$GITHUB_SHA

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Yandex Cloud CLI
              run: |
                  curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash && \
                  exec $SHELL && \
                  yc --version
            - name: Login to Yandex Registry
              uses: docker/login-action@v2
              with:
                  registry: cr.yandex
                  username: json_key
                  password: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
            - name: Create .env file
              run: echo ${{ secrets.ENV_FILE }} > .env
            - name: Build image
              run: docker build -t ${{ env.IMAGE_TAG }} .
            - name: Push image
              run: docker push ${{ env.IMAGE_TAG }}

    deploy:
        runs-on: self-hosted
        needs: build
        steps:
            - name: Stop container
              run: |
                  docker stop ${{ env.REPO_NAME }}
            - name: Deploy to server
              if: ${{ always() }}
              run: |
                  docker run -d --rm -p 3000:3000 --name ${{ env.REPO_NAME }} ${{ env.IMAGE_TAG }}
